### PR TITLE
Q1 106 flashcards monorepo

### PR DESCRIPTION
**Pull request by ToJestKrzysio**
# Description
Monorepo access for flashcards

Fixes # [(issue)](https://azeno.youtrack.cloud/issue/AQ-106/Test-Monorepo-with-Flashcards)

## Type of change

Please delete options that are not relevant.

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] The related memme has been added

image

### CODE REVIEW

**Review by lurco — COMMENTED** [review]
Flashcardów niestety nie byłem w stanie postawić... Wygląda tak, jakby docker wywalał się na etapie ładowanie poetry, ale nie jestem pewien.

**Comment by ToJestKrzysio** [comment]
Tylko część frontowa była zmieniana :smile:

**Comment by MWasile** [comment]
śmiga aż miło 🥇

**Review by MWasile — APPROVED** [review]
śmiga aż miło 🥇

**Pull request merged**
