### PR TITLE
Af 35 api

### PR DESCRIPTION
**Pull request by annagorkiewicz**
# Description

Add viewset with list and retrieve methods to allow listing all decks and viewing one deck with details.
YouTrack Ticket AF-35: [YouTrack Link](https://azeno.youtrack.cloud/issue/AF-35/api)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Manually (via Postman, collection added to the ticket in YouTrack) and Pytest

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] The related meme has been added

Meme

### CODE REVIEW

**Review by MWasile — CHANGES_REQUESTED** [review]
[This](https://github.com/AzenoIT/azeno/blob/2020063c76fa373d865d28811bc4b79b53aa727f/flashcards/backend/config/settings.py#L177) needs to be removed from the code, otherwise it will cause errors for me.
```
 ImportError: Could not import 'drf_spectacular.openapi.AutoSchema' for API setting 'DEFAULT_SCHEMA_CLASS'. ModuleNotFoundError: No module named 'drf_spectacular'.
````

code works fine, but I would suggest improving the view to return category as a complete object instead of just its ID

**Comment by martynawitkowska** [comment]
I suggest serving API through proxy, because right now only backend can use it 😅

**Comment by annagorkiewicz** [comment]
- removed drf-spectacular reference from settings file
- added CategorySerializer and display of category fields in Deck view
- added new assertion in test case to check for category name in response data

**Comment by annagorkiewicz** [comment]
Added location /api/v1/ to proxy/default.conf to use API through proxy

**Review by MWasile — APPROVED** [review]
Good job ;)

**Review by habibuga — COMMENTED** [review]
Looks good :smiley: 
It turns out that we have a duplicate task [FM-37](https://azeno.youtrack.cloud/issue/FM-37/All-decks-API) Only the requirement  there was to add the default sorting by deck popularity for the deck list. Would you like to add it in your task so that I could close FM-37?

**Review by aluczakzero — APPROVED** [review]
Nice work  :)

**Comment by annagorkiewicz** [comment]
Added sorting list by popularity: List returned by api is now sorted, most popular decks are on top of the returned list.

**Comment by annagorkiewicz** [comment]
Updated to sort by rating, squashed with last commit :)

**Review by habibuga — APPROVED** [review]
Good job!
Deck list works, sorting by rating also works.

**Pull request merged**
