### PR TITLE
AQ-79 badge endpoint

### PR DESCRIPTION
**Pull request by martynawitkowska**
# Description

1. Endpoint for a single badge.
2. Endpoint for list of all badges.
3. Inline badge for player in admin panel.
4. Badge DB fixtures, NOTE: the images urls will be present in db but won't work.
5. Postman collection is available in this [YouTrack Issue](https://azeno.youtrack.cloud/issue/AQ-79)

Fixes # (issue)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Manually and unit tests.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] The related memme has been added

GetBadges

### CODE REVIEW

**Review by SlawCzech — APPROVED** [review]
Reviewed and run the code, but was unable to pinpoint any shortcomings. Well done :)

**Comment by MWasile** [comment]
Great job :) There's small error in the postman collection in the URL in case anyone missed it :)

**Review by MWasile — APPROVED** [review]
Great job :) There's small error in the postman collection in the URL in case anyone missed it :)

**Comment by martynawitkowska** [comment]
@MWasile can you please point the error, because I missed it? 😂

**Review by MWasile — CHANGES_REQUESTED** [review]
edit: missclick

**Review by MWasile — APPROVED** [review]

**Review by annagorkiewicz — APPROVED** [review]
Great job! Everything works :)

**Pull request merged**
