### PR TITLE
Aq 103 setup monorepo

### PR DESCRIPTION
**Pull request by ToJestKrzysio**
# Description
Configured monorepo for more details consult all knowing NPM being.

Fixes # (issue)

## Type of change

Please delete options that are not relevant

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] The related memme has been added

image
image

### CODE REVIEW

**Comment by ToJestKrzysio** [comment]
Monorepo works for quiz, although throws some errors for mobile. Will have to integrate mobile as part of monorepo in next stages.

**Comment by ToJestKrzysio** [comment]
Example use case

```tsx
import { Button } from "@azeno/bank/src/components/"

// If replace function in App.tsx application should display blue button.
function App() {
    return <Button onClick={() => console.log(42)}>Hello World!<Button>
}
```

**Review by MWasile — APPROVED** [review]
imports from @azeno/bank/scr/components work fine. Storybook is also working correctly. Good job :)
Screenshot 2023-04-19 at 18 52 34

**Review by pawelkonior — APPROVED** [review]
Działa, ale nie powiem, trzeba się będzie zastanowić nad lepszymi rozwiązaniami architektonicznymi, bo czuje jak mi się w pokoju grzeje ;)

**Comment by ToJestKrzysio** [comment]
Jak mówiłem build szybki nie jest, na szczęście często go robić nie trzeba.

**Pull request merged**
